# Generated by Django 3.0.2 on 2020-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_id', models.IntegerField()),
                ('plano', models.CharField(max_length=42)),
                ('canal', models.CharField(max_length=42)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
